"""The provider must import cleanly against stock aitw — no fork-only paths.

Snapshots the set of ``aitw.*`` modules present in the stock baseline and asserts
that importing ``provider`` (and the ``defense`` package it pulls in) never imports
anything outside that set.
"""

from __future__ import annotations

import sys


# The set of aitw.* module names that are part of the published stock baseline
# (day-zerodev/aitw-target). This was generated by enumerating the installed
# stock package via pkgutil.walk_packages.
STOCK_AITW_MODULES = {
    "aitw",
    "aitw.agent",
    "aitw.agent.adapters",
    "aitw.agent.adapters.anthropic_adapter",
    "aitw.agent.adapters.base",
    "aitw.agent.adapters.mock_adapter",
    "aitw.agent.loop",
    "aitw.agent.profile",
    "aitw.context",
    "aitw.context.store",
    "aitw.logging",
    "aitw.logging.observation_log",
    "aitw.orchestrator",
    "aitw.orchestrator.admin",
    "aitw.orchestrator.app",
    "aitw.orchestrator.run_harness",
    "aitw.safety",
    "aitw.safety.reset",
    "aitw.safety.secret_guard",
    "aitw.scenarios",
    "aitw.scenarios.base",
    "aitw.scenarios.fixtures",
    "aitw.scenarios.ops_summary",
    "aitw.scenarios.research_assistant",
    "aitw.scenarios.support_triage",
    "aitw.tools",
    "aitw.tools.broad_tool",
    "aitw.tools.file_io",
    "aitw.tools.http_fetch",
    "aitw.tools.instruction_tool",
    "aitw.tools.registry",
    "aitw.tools.scheduler",
    "aitw.tools.send_email",
    "aitw.tools.shared_memory",
    "aitw.tools.web_search",
}


def _aitw_modules_in_sys() -> set[str]:
    return {n for n in sys.modules if n == "aitw" or n.startswith("aitw.")}


def test_provider_imports_only_stock_aitw_modules():
    # Drop any prior aitw imports so we get a clean snapshot of what *this* import pulls in.
    for name in list(sys.modules):
        if name == "provider" or name.startswith("defense"):
            del sys.modules[name]

    before = _aitw_modules_in_sys()

    import provider  # noqa: F401 — import for side effect
    from defense import (  # noqa: F401
        broker,
        bulletin,
        policy_registry,
        sanitizer,
        scanner,
        scoped_store,
    )
    # Touch task_registry to force the lazy tool-module imports.
    from aitw.tools.registry import ToolContext
    dep = provider.DEPLOYMENT
    raw_store = _build_raw_store()
    scoped = dep.wrap_store(raw_store, "alpha")
    ctx = _build_min_ctx(scoped)
    dep.task_registry(ctx, scanner=dep.make_scanner(), credential_guard=None)

    after = _aitw_modules_in_sys()
    new_imports = after - before

    fork_only = new_imports - STOCK_AITW_MODULES
    assert fork_only == set(), (
        "Fork-only aitw imports leaked into provider load — this WILL fail on "
        "the operator's clean host: " + ", ".join(sorted(fork_only))
    )


def _build_raw_store():
    from aitw.context.store import ContextStore
    return ContextStore(":memory:")


def _build_min_ctx(scoped):
    from dataclasses import dataclass, field
    from pathlib import Path
    from aitw.tools.registry import ToolContext

    @dataclass
    class _P:
        tenant_id: str = "alpha"
        allowed_tools: list = field(default_factory=lambda: ["shared_memory"])

        def system_prompt(self):
            return ""

    return ToolContext(
        tenant_id="alpha",
        workspace=Path("/tmp"),
        store=scoped,
        egress_allowlist=[],
        profile=_P(),
    )
